### ISSUE TITLE
Vimux always uses nearest Tmux pane instead of creating its own.

### ISSUE THREAD

**Issue by g-rutter** [benmills/vimux#103]
The docs say that setting

```vim
let VimuxUseNearestPane = 0
```

Will force vimux to create its own pane for running my commands, instead of putting them in an existing nearby Tmux pane. In my experience, this has no effect. The only way I can get vimux to create its own pane is by having no other panes open for use.

**Comment by sitaktif** [comment]
@g-rutter The documentation mentions `g:VimuxUseNearest` but not `g:VimuxUseNearestPane`.

Starting a new tmux session, running `vim`, creating a tmux split pane, focusing Vim back, calling `:let g:VimuxUseNearest = 0`, then calling `:call VimuxRunCommand("echo 42")` *does* create a third pane (omitting the reset of `g:VimuxUseNearest`, the command would instead be run on the pane I have created and not create a third one).

Can you please try to reproduce and potentially close the bug?

**Comment by g-rutter** [comment]
Yes, that fixes it. Looks like the docs have been updated.

**Comment by alexzanderr** [comment]
does work for me with `let g:VimuxUseNearest = 0`

my vimux config:
```
let g:VimuxHeight = "50"
let g:VimuxOrientation = "h"
let g:VimuxOpenExtraArgs = "-b"
let g:VimuxUseNearest = 0


let g:VimuxCloseOnExit = 1
let g:VimuxPromptString = "enter command for tmux splitted pane: "
let g:VimuxRunnerName = "vscode-code-runner"

```

**Comment by alexzanderr** [comment]
> you should also try [my fork](https://github.com/yunake/vimux), it uses IDs instead of indexes of reference tmux objects, perhaps that's your problem (although as far as I can tell the code in this repo should work too)

your fork doesnt even work with all the standard vimux configs...
