### ISSUE TITLE
Allow using a specific pane/window for tests

### ISSUE THREAD

**Issue by michaelmior** [benmills/vimux#128]
It would be nice if it were possible to name a pane or window and then have vimux always use that window. For example, I'd like to have a separate window of my tmux session open on a second monitor with a window for test results. Then any vim windows should always use this window for vimux. It seems like it's not currently possible to guarantee that a particular window will always be used.

**Comment by dkrieger** [comment]
@michaelmior  This isn't exactly what you are asking for, but if you revert one of the commits it adds (9ec2d6), you could get very similar behavior to what you describe.

**Comment by michaelmior** [comment]
@dkrieger Thanks! I'll close this since it seems like your PR will resolve this issue.

**Comment by dkrieger** [comment]
@michaelmior let me know if it doesn't work, but so long as they share the same session I think it will work. It looks like Ben Mills hasn't been active on GH for a while, feel free to use my fork as I'll keep it up to date with upstream until/unless the PR is accepted
