### ISSUE TITLE
How to send text from vim to a tmux pane?

### ISSUE THREAD

**Issue by gBopHuk** [benmills/vimux#136]
I see you removed VimuxSendText. How to send text to a tmux pane at now?

**Comment by english** [comment]
@gBopHuk `VimuxSendText` [still exists](https://github.com/benmills/vimux/blob/2285cefee9dfb2139ebc8299d11a6c8c0f21309e/plugin/vimux.vim#L55-L57).

[There's a section in the documentation](https://github.com/benmills/vimux/blob/2285cefee9dfb2139ebc8299d11a6c8c0f21309e/doc/vimux.txt#L246-L271) explaining how to set up a couple of mappings to use `VimuxSendText`. I've just pasted the following into my `.vimrc` and I'm able to send Ruby code from my buffer to a `pry` session running in a tmux pane:

```vi
function! VimuxSlime()
  call VimuxSendText(@v)
  call VimuxSendKeys("Enter")
endfunction

" If text is selected, save it in the v buffer and send that buffer it to tmux
vmap <Leader>vs "vy :call VimuxSlime()<CR>

" Select current paragraph and send it to tmux
nmap <Leader>vs vip<LocalLeader>vs<CR>
```

**Comment by dkrieger** [comment]
@gBopHuk or use https://github.com/tpope/vim-tbone (I use both)

**Comment by timjstewart** [comment]
BTW I found the difference between ipython and python interesting.

After running `VimuxRunCommand "ipython"`,  I select the following Python code inside of vim:

`def flappy():
    num = 1
    print(num * num)
`
and then hit <leader>vs, I see the following in iPython's shell:

`In [20]: def flappy():
    ...:         num = 1                                                                                                                                                    
    ...:             print(num * num)
  File "<ipython-input-20-e69ed03d3e2a>", line 3
    print(num * num)
    ^                                      
IndentationError: unexpected indent`

This works fine in plain old python's REPL.  iPython must be inserting its own indentation.  Sounds like I need a custom version of VimuxSlime() for when the target does indentation automatically.

**Comment by ostera** [comment]
Closing this question as it was answered by @english.
