### ISSUE TITLE
Vimux isn't working

### ISSUE THREAD

**Issue by aruzmeister** [benmills/vimux#137]
I have already installed the vimux
`Plug 'benmills/vimux'` in `.vimrc` but it's not loading when i do 
it says `Unkown function: FunVimTmuxCommand`

**Comment by benmills** [comment]
Hey @aruzmeister thanks for the issue! `FunVimTmuxCommand` isn't a command. Check out the docs to see the full list of commands[1]. I think you want `VimuxRunCommand()` if you're using a function or `VimuxPromptCommand` if you want to call it as a command.

In vim, if you type `:Vimux<tab>` you should be able to see the commands available. Or if you type `:call Vimux<tab>` you can see the functions available. 

[1] https://github.com/benmills/vimux/blob/master/doc/vimux.txt#L63
