### ISSUE TITLE
Repo Maintenance?

### ISSUE THREAD

**Issue by azure-satellite** [benmills/vimux#153]
I looked through contributions and found you guys. This repo seems to be unmaintained. Would anyone care to adopt it? I can't because of personal reasons.

**Comment by azure-satellite** [comment]
@jhulick @jingweno @johnhampton @johnsonch @jonaustin @jtdowney @jtmkrueger @justone @KabbAmine @kavinderd @kevinjqiu @KevinSjoberg @larrylv @learn-alex @lengarvey @lfendy-vim @libanp @lingceng @lyuts @m42e @mhs-student-01 @Murlocks @musoke @mwidz @mxie @myinitialsarepm @NICKLAB @NickLaMuro @nikhgupta @noscripter @notahat @nwertman @nytthea @optionalg @Ortuna @oscardelben @ostera @pgr0ss @phinze @pmahent @ppalucki @prognostikos @pythonxy @rainux @rowhit @shahratin @sitaktif @slowkow @spiegela @sumeet @sxhao @t6d @temcom @teoric @thalesmello @thatchristoph @theeternalsw0rd @thejspr @three3q @ton @tony-kunliu @tonyc @tonyskn @trbrink @trevorwhitney @trootski @tungel @vitillo @walterfrs @wellbredgrapefruit @weynhamz @wilywampa @wjdix @xingyuqi @xuxiaodong @Yixf-Self @yunake
I looked through contributions and found you guys. This repo seems to be unmaintained. Would anyone care to adopt it? I can't because of personal reasons.

**Comment by azure-satellite** [comment]
@sxhao @t6d @temcom @teoric @thalesmello @thatchristoph @theeternalsw0rd @thejspr @three3q @ton @tony-kunliu @tonyc @tonyskn @trbrink @trevorwhitney @trootski @tungel @vitillo @walterfrs @wellbredgrapefruit @weynhamz @wilywampa @wjdix @xingyuqi @xuxiaodong @Yixf-Self @yunake
I looked through contributions and found you guys. This repo seems to be unmaintained. Would anyone care to adopt it? I can't because of personal reasons.

**Comment by azure-satellite** [comment]
@520lly @abstiles @adeluccar @alepez @alexlegg @alindeman @alols @andybeeching @anyakichi @bhipple @birnam @bnadlerjr @bsmr-vim @chauncey-garrett @chip @chu- @chunaife @cloud8421 @cmar @configs-alexuser01 @danfinkelstein @daniely @danyoon-sge @daviddavis @dkrieger @drewrockshard @eagle0701 @eks @elight @elmosanches @emidln @ersatzryan @evoup @fabiomcosta @FClad @felixpalmer @fishman @fpereira1 @Fresne @grissomlau @grota @hihihippp @igs-awilliams @iwataka @jajm @JamesKid @javier86 @jchain @jdavis @jerri

**Comment by ostera** [comment]
Dibs! I use it fairly often -- wouldn't mind stepping up and sharing the
responsibilities with someone else for failover.
lör 17 juni 2017 kl. 17:51 skrev Alejandro Hernandez <
notifications@github.com>:

**Comment by azure-satellite** [comment]
Sweet! Then we should let this issue open for people to be aware of sending their pull requests to you. Thanks!

**Comment by benmills** [comment]
Thanks for creating this issue. It's true I've been unable to maintain my OS projects anymore. @ostera it might be easist to give you commit access, but happy to do whatever makes the most sense.

**Comment by ostera** [comment]
@benmills I think that's the right thing to do now too.

Imagine all the broken vimrc's complains arising from moving this repo haha chaos.

**Comment by daniely** [comment]
Thanks @azure-satellite and @ostera for not letting the project die. Really appreciate it.

**Comment by yunake** [comment]
i use vimux all the time, or rather my fork of it since i couldn't get my patch in. thank you for stepping up @ostera! perhaps now i can migrate back to upstream

**Comment by azure-satellite** [comment]
Any word on merging the outstanding pull requests?

**Comment by azure-satellite** [comment]
I could also review and merge in the meantime. I can't be a maintainer for the long run but I could step up together with @ostera for the next month or so.

**Comment by ostera** [comment]
I still don't have privileges over the repository, so not much I can do until @benmills gives me access to it.

**Comment by azure-satellite** [comment]
@benmills?

**Comment by m42e** [comment]
@ostera @benmills @azure-satellite 

What about creating a vimux organisation? and offer it under vimux/vimux?

**Comment by musoke** [comment]
If the repo is transferred to an org it may not even break existing 
configurations - as far as I know GitHub does redirects until a new repo 
with the old path is created.

**Comment by benmills** [comment]
I just added @ostera as a collaborator, once he accepts he should have rights to address these things.

**Comment by ostera** [comment]
@m42e @musoke while I favour the idea of having an organisation, I'd propose to revisit after we go through the bulk of PR's and Issues that are more pressing. Github may support redirects but I've had problems in the past with tools that don't know what to do with a HTTP 301.

@azure-satellite if you'd like, feel free to take a look at some of the PR's and leave a Github Review -- it would make it easier to go ahead and merge some of them if a pair of eyes have screened them already :)

Other than that, thanks to @benmills for the opportunity, and let's make sure vimux continues to kick ass.

I think we are good here now 👌

**Comment by m42e** [comment]
@ostera fine for me! So, let's go.

**Comment by jerri** [comment]
Did this project die? Or was it moved to another fork?
