### ISSUE TITLE
You should add more things to the doc.

### ISSUE THREAD

**Issue by l13rb4git** [benmills/vimux#175]
I've been search for a way to run commands with more than one expand() using VimuxRunCommand.
Fortunately I find out that the little dot is the separator.
Ex: `:call VimuxRunCommand("clear; gcc " . expand("%") . " -o " . expand("%:r") . " ; ./" . expand("%:r"))`

Tanks you for the plugin, it's really useful!

**Comment by mvcouwen** [comment]
This is not really a feature of vimux, but rather of vim itself. Dots are used to concatenate strings in any vimscript. See `:help expression-syntax`. Is this not clear from the example under `:help VimuxRunCommand`?
