### ISSUE TITLE
omit character "`" when using \vs

### ISSUE THREAD

**Issue by kepbod** [benmills/vimux#57]
As I mentioned in issue #39, vimux will omit " ` " when using \vs. Please also escape it before sending to the tmux. Thanks!

**Comment by lingceng** [comment]
I fixed the problem by adding " ` " to escape() in plugin/vimux.vim:
```
function! VimuxSendText(text)
  call VimuxSendKeys('"'.escape(a:text, '`\"$').'"')
endfunction
```
