### ISSUE TITLE
doesn't work at all 

### ISSUE THREAD

**Issue by pinggit** [benmills/vimux#98]
after i issue any command, nothing  happened. no success, no errors, just like nothing happened....I'm running ubuntu12.04 and vim 7.4

**Comment by inside** [comment]
I just installed vimux and ran :VimuxRunCommand('ls'), it opened a tmux pane and ran ls in it.
FYI, you have to be running vim inside a tmux session.

@pinggit can you close this issue if you find its not relevant anymore?

**Comment by ostera** [comment]
Considering this is fairly old and virtually irreproducible, I'll close this issue. @pinggit feel free to reopen if you manage to reproduce 😃
